version: "3.7"

services:

  flask:
    build: ./flask
    expose:
      - 8080
    environment:
      - TZ=Asia/Taipei

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask
